apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    # - name: sams-port
    #   port: 8080
    #   targetPort: 80
    - name: postgres-port
      port: 8080
      targetPort: 5432
