apiVersion: v1
kind: Service
metadata:
  name: sams-service
spec:
  selector:
    app: sams-app
  ports:
    - name: sams-port
      port: 8080
      targetPort: 80
    # - name: postgres-port
    #   port: 8090
    #   targetPort: 5432
