apiVersion: {{.Values.apiVersionDeployment}}
kind: {{.Values.postgresDeployment.kind}}
metadata:
  name: {{.Values.postgresDeployment.name}}
  labels:
    app: {{.Values.postgresDeployment.labels.app}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.postgresDeployment.labels.app}}
  template: #this here is the blueprint of a postgres pod
    metadata:
        labels:
          app: {{.Values.postgresDeployment.labels.app}}
    spec:
      containers:
      - name: {{.Values.postgresDeployment.containers.name}}
        image: {{.Values.postgresDeployment.containers.image}}
        ports:
        - name: {{.Values.postgresDeployment.ports.name}}
          containerPort: {{.Values.postgresDeployment.ports.port}}
        env:
        - name: {{.Values.postgresDeployment.env.password}}
          value: {{.Values.postgresDeployment.env.passwordvalue}}
        - name: {{.Values.postgresDeployment.env.user}}
          value: {{.Values.postgresDeployment.env.uservalue}}